
UNUSED_PRETRAINED_LAYERS = ['"fc_1.weight", '
                            '"fc_1.bias", '
                            '"fc_2.weight", '
                            '"fc_2.bias", '
                            '"fc_3.weight", '
                            '"fc_3.bias", '
                            '"fc_4.weight", '
                            '"fc_4.bias", '
                            '"bn_1.weight", '
                            '"bn_1.bias", '
                            '"bn_1.running_mean", '
                            '"bn_1.running_var", '
                            '"bn_1.num_batches_tracked", '
                            '"bn_2.weight", "bn_2.bias", '
                            '"bn_2.running_mean", '
                            '"bn_2.running_var", '
                            '"bn_2.num_batches_tracked", '
                            '"bn_3.weight", "bn_3.bias", '
                            '"bn_3.running_mean", '
                            '"bn_3.running_var", '
                            '"bn_3.num_batches_tracked", '
                            '"bn_4.weight", '
                            '"bn_4.bias", '
                            '"bn_4.running_mean", '
                            '"bn_4.running_var", '
                            '"bn_4.num_batches_tracked"']